-- TABLES
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- COLUMNS
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

-- COUNTRIES
SELECT DISTINCT country FROM gold.dim_customers

-- CATEGORIES
SELECT DISTINCT category,subcategory,product_name 
FROM gold.dim_products
ORDER BY 1,2,3

-- TIMESPAN
SELECT  MIN(order_date) AS First_Order_Date,
		MAX(order_date) AS Last_Order_Date,	
		DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) AS Year_Span
FROM gold.fact_sales

-- TOTAL SALES
SELECT SUM(sales_amount) AS Total_Sale FROM gold.fact_sales

-- TOTAL QUANTITY
SELECT SUM(quantity) AS Toal_Items_Sold FROM gold.fact_sales

-- AVERAGE SALE PRICE
SELECT SUM(sales_amount)/SUM(quantity) AS Average_Sale_Price FROM gold.fact_sales

-- TOTAL ORDERS
SELECT COUNT(DISTINCT order_number) AS Total_Orders FROM gold.fact_sales

-- TOTAL PRODUCTS
SELECT COUNT(DISTINCT product_key) AS Total_Products FROM gold.fact_sales

-- TOTAL CUSTOMERS
SELECT COUNT(DISTINCT customer_key) AS Total_Customers FROM gold.fact_sales

-- EXPLOARTION TABLE
SELECT 'Total Sales' AS Measure, SUM(sales_amount) AS Value FROM gold.fact_sales
UNION ALL
SELECT 'Total Items Sold', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price per Item',SUM(sales_amount)/SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_key) FROM gold.fact_sales
UNION ALL
SELECT 'Total Customers', COUNT(DISTINCT customer_key) FROM gold.fact_sales

-- Customers from each Country
SELECT country, COUNT(DISTINCT customer_id) AS Number_of_Customers
FROM gold.dim_customers
GROUP BY country
ORDER BY Number_of_Customers DESC

-- Customers from each Gender
SELECT gender, COUNT(DISTINCT customer_id) AS Number_of_Customers
FROM gold.dim_customers
GROUP BY gender

-- Products in each Category
SELECT category, COUNT(product_key) AS Number_of_Products
FROM gold.dim_products
GROUP BY category
ORDER BY Number_of_Products DESC

-- Average Cost for each Category
SELECT category, AVG(cost) AS Average_Cost
FROM gold.dim_products
GROUP BY category
ORDER BY Average_Cost DESC

-- Total Revenue generated for each Category?
SELECT Products.category, SUM(Sales.sales_amount) AS Revenue 
FROM gold.fact_sales Sales
LEFT JOIN gold.dim_products Products
	ON Sales.product_key = Products.product_key
GROUP BY category

-- Revenue Generated by each Customer?

SELECT Customers.customer_id,
	CONCAT(Customers.first_name,' ',Customers.last_name) AS Customer_Name,
	SUM(Sales.sales_amount) AS Revenue
FROM gold.fact_sales Sales
LEFT JOIN gold.dim_customers Customers
	ON Sales.customer_key = Customers.customer_key
GROUP BY customer_id,first_name,last_name
ORDER BY Revenue DESC
